package drools
import org.enoir.rulest.sample.SampleFact

rule "Hello World"
    when
        m : SampleFact( status == 1, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye world" );
        m.setStatus( 0 );
        update( m );
end

rule "GoodBye"
    when
        SampleFact( status == 0, myMessage : message )
    then
        System.out.println( myMessage );
end