package drools
import org.enoir.rulest.model.Fact
declare Message
    message: String
    status: int
end

rule "Hello World"
    when
        m : Message( status == 1, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye world" );
        m.setStatus( 0 );
        update( m );
end

rule "GoodBye"
    when
        Message( status == 0, myMessage : message )
    then
        System.out.println( myMessage );
end